[profile.release]
panic = 'unwind'

[workspace]
members = [
	'node',
	'pallets/*',
	'runtime',
	"open-runtime-module-library/currencies",
	"open-runtime-module-library/tokens",
	"open-runtime-module-library/traits",
	"open-runtime-module-library/utilities",
]
